{"version":1,"defects":{"Lett\\Tests\\LettTest::it_can_report_an_exception_to_lett":7,"Lett\\Tests\\TestCommandTest::it_detects_that_its_running_in_the_correct_environment":7,"Lett\\Tests\\TestCommandTest::it_detects_that_it_fails_to_send_to_lett":7},"times":{"Lett\\Tests\\Fakes\\LettFakeTest::it_will_sent_exception_to_let_if_exception_is_thrown":0.025,"Lett\\Tests\\Fakes\\LettFakeTest::it_will_sent_nothing_to_let_if_no_exceptions_thrown":0.001,"Lett\\Tests\\LettTest::is_will_not_crash_if_let_returns_error_bad_response_exception":0.004,"Lett\\Tests\\LettTest::is_will_not_crash_if_let_returns_normal_exception":0.001,"Lett\\Tests\\LettTest::it_can_skip_exceptions_based_on_class":0,"Lett\\Tests\\LettTest::it_can_skip_exceptions_based_on_environment":0,"Lett\\Tests\\LettTest::it_will_return_false_for_sleeping_cache_exception_if_disabled":0,"Lett\\Tests\\LettTest::it_can_check_if_is_a_sleeping_cache_exception":0.001,"Lett\\Tests\\LettTest::it_can_get_formatted_exception_data":0.001,"Lett\\Tests\\LettTest::it_filters_the_data_based_on_the_configuration":0,"Lett\\Tests\\LettTest::it_can_report_an_exception_to_lett":0.003,"Lett\\Tests\\LoggingTest::it_will_not_send_log_information_to_lett":0.006,"Lett\\Tests\\LoggingTest::it_will_only_send_throwables_to_lett":0.002,"Lett\\Tests\\TestCommandTest::it_detects_if_the_login_key_is_set":0.026,"Lett\\Tests\\TestCommandTest::it_detects_if_the_project_key_is_set":0.005,"Lett\\Tests\\TestCommandTest::it_detects_that_its_running_in_the_correct_environment":0.004,"Lett\\Tests\\TestCommandTest::it_detects_that_it_fails_to_send_to_lett":0.004,"Lett\\Tests\\UserTest::it_return_custom_user":0.001,"Lett\\Tests\\UserTest::it_return_custom_user_with_to_lett":0,"Lett\\Tests\\UserTest::it_returns_nothing_for_ghost":0}}